### PR TITLE
Ready: Powershell make

### PR DESCRIPTION
**Pull request by lukebakken**
Advantages:

* `Get-Help .\make.ps1 -Full` :clap:
* Parameter validation
* Smarter about finding `MSBuild.exe`

### CODE REVIEW

**Comment by alexmoore** [comment]
image

**Comment by alexmoore** [comment]
Missing "DeprecatedTest" from help listing.

**Comment by lukebakken** [comment]
@alexmoore I figured that end-users wouldn't be as interested in that and other target that really are for our use. `DeprecatedTest` is still part of the `ValidateSet` for the `Target` parameter, however. Let me know if you'd like it added to the help.

**Comment by alexmoore** [comment]
+1 then, cheerio!

**Pull request merged**
